---
- name: Install nfs utils packages
  package:
    name: "{{ item.name }}"
    state: present
    use: "{{ item.use }}"
  loop:
    - {name: "rpcbind", group: "storage", os: "Ubuntu", use: "apt"}
    - {name: "nfs-kernel-server", group: "kubernetes", os: "Ubuntu", use: "apt"}
    - {name: "rpcbind", group: "storage", os: "CentOS", use: "yum"}
    - {name: "nfs-utils", group: "kubernetes", os: "CentOS", use: "yum"}
  when:
    - enable_nfs | bool
    - inventory_hostname in groups[item.group]
    - ansible_distribution == item.os

- name: Install haproxy and keepalived
  package:
    name:
      - haproxy
      - keepalived
    state: present
  when:
    - enable_haproxy | bool
    - inventory_hostname in groups['haproxy']

- name: Hanlder the kubernetes stuffs
  block:
    - name: Copy container runtime repos for kubernetes nodes
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - {"src": docker-ce.repo.j2, "dest": /etc/yum.repos.d/docker-ce.repo, os: "CentOS"}
        - {"src": kubernetes.repo.j2, "dest": /etc/yum.repos.d/kubernetes.repo, os: "CentOS"}
        - {"src": sources.list.j2, "dest": /etc/apt/sources.list, os: "Ubuntu"}
      when:
        - ansible_distribution == item.os

    - name: Distribute docker and kubernetes gpg keys
      copy:
        src: "{{ item }}"
        dest: "/tmp/{{ item }}"
      loop:
        - docker.gpg
        - kubernetes.gpg
      when:
        - ansible_distribution == 'Ubuntu'

    - name: Add docker and kubernetes gpg keys
      shell: apt-key add "/tmp/{{ item }}"
      become: true
      loop:
        - docker.gpg
        - kubernetes.gpg
      changed_when: false
      when:
        - ansible_distribution == 'Ubuntu'

    - name: Update ubuntu source
      apt:
        update_cache: yes
      when:
        - ansible_distribution == 'Ubuntu'

    - name: Install kubernetes and its indepent packages
      package:
        name: "{{ item.name }}"
        state: present
        use: "{{ item.use }}"
      loop:
        - {name: "kubelet={{ kube_release_ubuntu }}", os: "Ubuntu", use: "apt"}
        - {name: "kubectl={{ kube_release_ubuntu }}", os: "Ubuntu", use: "apt"}
        - {name: "kubeadm={{ kube_release_ubuntu }}", os: "Ubuntu", use: "apt"}
        - {name: "kubelet-{{ kube_release }}", os: "CentOS", use: "yum"}
        - {name: "kubectl-{{ kube_release }}", os: "CentOS", use: "yum"}
        - {name: "kubeadm-{{ kube_release }}", os: "CentOS", use: "yum"}
      when:
        - ansible_distribution == item.os

    # Somethings service module invoke enable command failed,
    # but I do not know the reason, use shell module to avoid.
    # The failed message is like:
    # "Could not find the requested service kubelet: host"
    - name: Enable kubelet service
      shell: systemctl enable kubelet
      changed_when: false
  when:
    - inventory_hostname in groups['kubernetes']

- name: Install docker and containerd runtimes
  package:
    name: "{{ item.runtime }}"
    state: present
    use: "{{ item.use }}"
  when:
    - inventory_hostname in groups[item.nodegroups] or
      inventory_hostname in groups[item.mastergroups]
    - ansible_distribution == item.os
  loop:
    - {runtime: "docker-ce={{ docker_release_ubuntu }}", nodegroups: "docker-node", mastergroups: "docker-master", os: "Ubuntu", use: "apt"}
    - {runtime: "containerd.io-{{ containerd_release }}", nodegroups: "containerd-node", mastergroups: "containerd-master", os: "Ubuntu", use: "apt"}
    - {runtime: "docker-ce-{{ docker_release }}.ce", nodegroups: "docker-node", mastergroups: "docker-master", os: "CentOS", use: "yum"}
    - {runtime: "containerd.io-{{ containerd_release }}", nodegroups: "containerd-node", mastergroups: "containerd-master", os: "CentOS", use: "yum"}

- name: Install common python modules
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ common_python_module }}"
  when:
    - inventory_hostname in groups['kubernetes']

- name: Ensure /etc/docker directories exists
  file:
    path: /etc/docker
    state: directory
  when:
    - inventory_hostname in groups['docker-master'] or
      inventory_hostname in groups['docker-node']

- name: Copy docker daemon jsons
  template:
    src: kube-daemon.json.j2
    dest: /etc/docker/daemon.json
  when:
    - inventory_hostname in groups['docker-master'] or
      inventory_hostname in groups['docker-node']
  notify:
    - Restart docker service

- name: Copy containerd config.toml
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
  when:
    - inventory_hostname in groups['containerd-master'] or
      inventory_hostname in groups['containerd-node']
  notify:
    - Restart containerd service

- name: Check docker service status
  service_check:
    service_name: docker
    service_type: systemd
  when:
    - inventory_hostname in groups['docker-master'] or
      inventory_hostname in groups['docker-node']
  notify:
    - Restart docker service

- name: Check containerd service status
  service_check:
    service_name: containerd
    service_type: systemd
  when:
    - inventory_hostname in groups['containerd-master'] or
      inventory_hostname in groups['containerd-node']
  notify:
    - Restart containerd service

- name: Flush handlers
  meta: flush_handlers
