apiVersion: v2
name: hpa-operator
version: 0.3.0
description: A Helm chart for Kubernetes
home: https://banzaicloud.com
sources:
  - https://github.com/banzaicloud/hpa-operator
keywords:
- hpa
- autoscale
