---
- name: Ensure kubernetes worker dir exists
  file:
    name: "{{ kube_application_dir }}"
    state: directory
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: True

- name: Apply kubernetes applications
  vars:
    kube_application: "{{ item.name }}"
    kube_enabled: "{{ item.enabled }}"
  include_role:
    role: kubectl-apply
  loop: "{{ kube_applications }}"

- include_tasks: setup_helm.yml
