---
- name: Ensure kubernetes worker dir not exists
  become: true
  file:
    name: "{{ kube_application_dir }}"
    state: absent
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: True

- name: Reset kubernetes nodes except the first node
  become: true
  kube_toolbox:
    module_name: kubeadm
    module_args: "reset -f"
  when: inventory_hostname != groups['kubernetes'][0]

- name: Reset the first node of kubernetes cluster
  become: true
  kube_toolbox:
    module_name: kubeadm
    module_args: "reset -f"
  when: inventory_hostname == groups['kubernetes'][0]

- name: Destroy loadbalancer role
  import_role:
    role: loadbalancer
  when: enable_kubernetes_ha | bool
