{{- if .Values.deployment.kong.enabled }}
{{- if .Values.admin.ingress.enabled -}}
{{- if .Values.admin.containerPort -}} {{/* TODO: remove legacy admin handling */}}
{{- $serviceName := include "kong.fullname" . -}}
{{- $servicePort := .Values.admin.servicePort -}}
{{- $path := .Values.admin.ingress.path -}}
{{- $tls := .Values.admin.ingress.tls -}}
{{- $hostname := .Values.admin.ingress.hostname -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "kong.fullname" . }}-admin
  namespace: {{ template "kong.namespace" . }}
  labels:
    {{- include "kong.metaLabels" . | nindent 4 }}
  {{- if .Values.admin.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.admin.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  rules:
  - host: {{ $hostname }}
    http:
      paths:
        - path: {{ $path }}
          backend:
            serviceName: {{ $serviceName }}-admin
            servicePort: {{ $servicePort }}
  {{- if $tls }}
  tls:
  - hosts:
    - {{ $hostname }}
    secretName: {{ $tls }}
  {{- end -}}
{{- else -}} {{/* Modern admin handler */}}
{{- $serviceName := include "kong.fullname" . -}}
{{- $servicePort := include "kong.ingress.servicePort" .Values.admin -}}
{{- $path := .Values.admin.ingress.path -}}
{{- $tls := .Values.admin.ingress.tls -}}
{{- $hostname := .Values.admin.ingress.hostname -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "kong.fullname" . }}-admin
  labels:
    {{- include "kong.metaLabels" . | nindent 4 }}
  {{- if .Values.admin.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.admin.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  rules:
  - host: {{ $hostname }}
    http:
      paths:
        - path: {{ $path }}
          backend:
            serviceName: {{ $serviceName }}-admin
            servicePort: {{ $servicePort }}
  {{- if $tls }}
  tls:
  - hosts:
    - {{ $hostname }}
    secretName: {{ $tls }}
  {{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
