# install chart with default values
# use single image strings instead of repository/tag

image:
  single: kong:2.0
proxy:
  type: NodePort

env:
  anonymous_reports: "off"
ingressController:
  env:
    anonymous_reports: "false"
  image:
    single: kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.8.1
  installCRDs: false
