# This tests the following unrelated aspects of Ingress Controller
# - HPA enabled
autoscaling:
  enabled: true
  args:
    - --alsologtostderr
# - ingressController deploys without a database (default)
ingressController:
  enabled: true
  installCRDs: false
# - webhook is enabled and deploys
  admissionWebhook:
    enabled: true
# - environment variables can be injected into ingress controller container
  env:
    anonymous_reports: "false"
    kong_admin_header: "foo:bar"
# - annotations can be injected for service account
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME
# - pod labels can be added to the deployment template
podLabels:
  app: kong
  environment: test
# - podSecurityPolicies are enabled
podSecurityPolicy:
  enabled: true
# - ingress resources are created with hosts
admin:
  type: NodePort
  ingress:
    enabled: true
    hosts: ["test.com", "test2.com"]
    annotations: {}
    path: /
proxy:
  type: NodePort
  ingress:
    enabled: true
    hosts: ["test.com", "test2.com"]
    annotations: {}
    path: /
env:
  anonymous_reports: "off"
