# This tests the following unrelated aspects of Ingress Controller
# - ingressController deploys with a database
ingressController:
  enabled: true
  installCRDs: false
  env:
    anonymous_reports: "false"
postgresql:
  enabled: true
  postgresqlUsername: kong
  postgresqlDatabase: kong
  service:
    port: 5432
env:
  anonymous_reports: "off"
  database: "postgres"
# - ingress resources are created without hosts
admin:
  type: NodePort
  ingress:
    enabled: true
    hosts: []
    path: /
proxy:
  type: NodePort
  ingress:
    enabled: true
    hosts: []
    annotations: {}
    path: /
  useTLS: true
# - add stream listens
  stream:
  - containerPort: 9000
    servicePort: 9000
    parameters: []
  - containerPort: 9001
    servicePort: 9001
    parameters:
    - ssl

# - PDB is enabled
podDisruptionBudget:
  enabled: true
# update strategy
updateStrategy:
  type: "RollingUpdate"
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
