---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: lint YAML files
        run: yamllint -s .

  markdown-lint:
    runs-on: ubuntu-latest
    container: pouchcontainer/pouchlinter:v0.1.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Run markdownlint misspell
      #   run: find  ./* -name  "*"  | xargs misspell -error

      - name: Lint markdown files
        run: find  ./ -name  "*.md" | xargs mdl -r ~MD001,~MD004,~MD005,~MD006,~MD007,~MD010,~MD013,~MD022,~MD023,~MD024,~MD029,~MD031,~MD032,~MD033,~MD034,~MD036

  pep8-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # E501 ignore line too long
          flake8 --ignore=E501

#      - name: Test with pytest
#        run: |
#          pytest

  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python3
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint==4.0.0
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # - name: Lint with ansible
      #   # Lint only code in ansible/* - ignore examples
      #   run: |
      #     ansible-lint -p --exclude=./examples .
